# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wu Han
title: A junior student in Sun Yat-sen University
email: wuhan36@mail2.sysu.edu.cn
website: www.g4alllf.xyz
website_title: Website Link

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  g4alllf
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi, my name's Wu Han and I'm a junior student in [the School of Software Engineering](https://sse.sysu.edu.cn/page/321), [Sun Yat-sen University](https://www.sysu.edu.cn/sysuen/).

    I am most skilled in: <mark>Mathematical Modeling</mark>, <mark>Machine Learning</mark> and <mark>Eating</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rust Online Judge
        sub_title: Our rust lesson project
        link: https://gitee.com/yangyf83/Rust-OnlineJudge
        link_text: Project Address
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An online judge beckend written in Rust 
        description: | # this will include new lines to allow paragraphs
            This is our <mark>Rust</mark> lesson project. We have learned many useful skills from this lesson and we're very proud of having the chance to apply the things we learned in this project. 
      
      - layout: left
        title: Blog
        sub_title: Our software engineering intermediate training lesson project
        link: https://gitee.com/gyau/intermediate-training-blog
        link_text: Project Address
        quote: >
          A blog system written by our team.
        description:
            This is our <mark>SSE Intermediate Training</mark> lesson project. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SYSU Scholarship
        sub_title: Second Prize Scholarship for undergraduates
        caption: October 2022
      
      - layout: top-middle
        title: KINGDOM CARES Scholarship
        sub_title: KINGDOM CARES Scholarship for undergraduates
        caption: October 2022
      
      - layout: left
        title: MCM
        link: https://www.comap.com/contests/mcm-icm
        link_text: Official Website
        sub_title: Finalist
        caption: September 2022
        quote: >
          Optimal allocation of reservior is closely related to economic and livelihood issues. Therefore, it's very important to formulate a reasonable allocation scheme to meet the regional demand.
        description: | # this will include new lines to allow paragraphs
            In reservior optimal operation, there are often problems of too many variables and too complex relationship between objectives, which makes it difficult for us to formulate a reasonable reservior operation strategy. In this contest, we proposed an optimal reservior scheduling scheme, and demonstrated the feasibility of the scheme. It's a great honor for our proposal to be nominated for the Finalist of the 2022 MCM Competition(Top 1% of all participants).
      
      - layout: top-middle
        title: SYSU-ICPC Novice trial
        sub_title: First Prize
        caption: September 2022

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sun Yat-sen University
        caption: 2020 - present
        sub_title: BEng Software Engineering
        quote: >
          Sun Yat-sen University is a national key public research university located in Guangdong, China.
        description: | # this will include new lines to allow paragraphs
            During my time at Sun Yat-sen University I learnt skills that are very important for my future career. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in ML and mathematical modeling some of my other interests and hobbies are:
      - Music
      - Gaming
      - Tennis

# Look at this cool image  
#   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
